name: update-gradlew

on:
  workflow_dispatch:
  schedule:
    # Every night at 5am
    - cron: "0 5 * * *"

jobs:
  update-gradlew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # The update-gradle-wrapper-action cannot work if we leave the default credentials.
          # See https://github.com/gradle-update/update-gradle-wrapper-action/issues/988
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Update Gradle wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          repo-token: ${{ secrets.GH_PAT }}
          labels: dependencies, internal
          merge-method: REBASE
